<div class="resultdiv">
         <div class="errordiv">
         <h2>Sorry, but renaming partially failed!</h2> <br />

                 <div style="text-align: center;">
                         <img src="<?php echo URL;?>/images/oops.jpg"/>
                 </div>
         <table width=100%>
                 <tr>
                         <td width=50%><h3><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>">>>back to step 1<<</a></h3></td>
                         <td width=50% style="text-align:right;"><h3><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'steptwo')) ?>">>>proceed with step 2<<</a></h3></td>
                 </tr>
         </table>
         </div>
</div>